#version: "1"
#services:
#
#  customer-db:
#    image: mysql
#    env_file:
#      - .env
#    networks:
#      - storenetwork
#    ports:
#      - 3306:3306
#
#  customer-app:
#    image: customer-image
#    env_file:
#      - .env
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - DB_URL=jdbc:mysql://localhost:3306/customerdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#        - DB_DATABASE=customerdb
#        - DB_USER=customeruser
#        - DB_PASSWORD=${DB_PASSWORD}
#    networks:
#      - storenetwork
#    ports:
#      - 8081:8081
#    depends_on:
#      - customer-db
#
#networks:
#  storenetwork:
