version: "3.9"

networks:
  storenetwork:

services:
  storeapi-customer-db:
    restart: unless-stopped
    image: mysql:latest
    environment:
      MYSQL_HOST: storeapi-customer-db
      MYSQL_DATABASE: customerdb
      MYSQL_USER: customeruser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - storenetwork

  storeapi-customer-app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ramenberg/storeapi-customer-image:latest
    ports:
      - "8081:8080"
    environment:
        MYSQL_HOST: storeapi-customer-db
        DB_DATABASE: customerdb
        DB_USER: customeruser
        DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - storenetwork
    depends_on:
      - storeapi-customer-db