version: "1.0"
services:
  customer-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: customerdb
      MYSQL_USER: customeruser
      MYSQL_PASSWORD: customerpassword
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - storenetwork

  customer-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_PASSWORD=customerpassword
    image: customer-image
    ports:
      - "8081:8080"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: customer-db
      DB_DATABASE: customerdb
      DB_USER: customeruser
      DB_PASSWORD: customerpassword
    networks:
      - storenetwork
    depends_on:
      - customer-db

networks:
  storenetwork: