version: "1"
services:
  mysql:
    image: customerdb
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
    networks:
      - customernetwork

  springboot:
    image: customer
    ports:
      - 8081:8081
    networks:
      - customernetwork

networks:
  customernetwork:
  itemsnetwork:
  ordersnetwork:
