spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DB_DATABASE:customerdb?characterEncoding=UTF-8}
    username: ${DB_USER:customeruser}
    password: ${DB_PASSWORD:customerpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: ${PORT:8080}
